SET SQL_SAFE_UPDATES = 0;
delete from likes;
ALTER TABLE likes AUTO_INCREMENT = 1;
delete from question;
ALTER TABLE question AUTO_INCREMENT = 1;
delete from participants;
ALTER TABLE participants AUTO_INCREMENT = 1;
delete from topic;
ALTER TABLE topic AUTO_INCREMENT = 1;
delete from stream;
ALTER TABLE stream AUTO_INCREMENT = 1;
delete from conference;
ALTER TABLE conference AUTO_INCREMENT = 1;
delete from user_roles;
ALTER TABLE user_roles AUTO_INCREMENT = 1;
delete from user;
ALTER TABLE user AUTO_INCREMENT = 1;
delete from participant_type;
ALTER TABLE participant_type AUTO_INCREMENT = 1;
delete from roles;
ALTER TABLE roles AUTO_INCREMENT = 1;
SET SQL_SAFE_UPDATES = 1;